# Generated by Django 4.2.8 on 2024-01-17 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('crypto_id', models.IntegerField(primary_key=True, serialize=False)),
                ('crypto_name', models.TextField(max_length=100)),
                ('crypto_symbol', models.TextField(max_length=100)),
                ('crypto_value', models.TextField()),
                ('crypto_date', models.DateField()),
                ('percent_change_7d', models.TextField()),
                ('crypto_value_TL', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('crypto_id', models.TextField()),
                ('stock_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_name', models.TextField(max_length=100)),
                ('stock_value', models.TextField(max_length=100)),
                ('stock_volume', models.TextField(max_length=100)),
                ('stock_rate', models.TextField(max_length=100)),
                ('stock_min', models.TextField(max_length=100)),
                ('stock_max', models.TextField(max_length=100)),
                ('stock_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=12, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 50 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('crypto_id', models.TextField()),
                ('crypto_amount', models.TextField()),
                ('stock_id', models.TextField()),
                ('stock_amount', models.TextField()),
            ],
        ),
    ]
