import styles from "./IllustrationBloggingBlogCo.module.css";

const IllustrationBloggingBlogCo = () => {
  return (
    <div className={styles.illustrationBloggingBlogCo}>
      <img className={styles.groupIcon} alt="" src="/group@2x.png" />
      <img className={styles.vectorIcon} alt="" src="/vector9@2x.png" />
      <img className={styles.vectorIcon1} alt="" src="/vector10@2x.png" />
      <img className={styles.vectorIcon2} alt="" src="/vector11@2x.png" />
      <img className={styles.vectorIcon3} alt="" src="/vector12@2x.png" />
      <img className={styles.vectorIcon4} alt="" src="/vector13@2x.png" />
      <img className={styles.vectorIcon5} alt="" src="/vector14@2x.png" />
      <img className={styles.vectorIcon6} alt="" src="/vector15@2x.png" />
      <img className={styles.vectorIcon7} alt="" src="/vector16@2x.png" />
      <img className={styles.vectorIcon8} alt="" src="/vector17@2x.png" />
      <img className={styles.vectorIcon9} alt="" src="/vector18@2x.png" />
      <img className={styles.vectorIcon10} alt="" src="/vector19@2x.png" />
      <img className={styles.vectorIcon11} alt="" src="/vector20@2x.png" />
      <img className={styles.vectorIcon12} alt="" src="/vector21@2x.png" />
      <img className={styles.vectorIcon13} alt="" src="/vector22@2x.png" />
      <img className={styles.vectorIcon14} alt="" src="/vector23@2x.png" />
      <img className={styles.vectorIcon15} alt="" src="/vector24@2x.png" />
      <img className={styles.vectorIcon16} alt="" src="/vector25@2x.png" />
      <img className={styles.vectorIcon17} alt="" src="/vector26@2x.png" />
      <img className={styles.vectorIcon18} alt="" src="/vector27@2x.png" />
      <div className={styles.wrapperVector}>
        <img className={styles.vectorIcon19} alt="" src="/vector28@2x.png" />
      </div>
      <div className={styles.wrapperVector1}>
        <img className={styles.vectorIcon20} alt="" src="/vector29@2x.png" />
      </div>
      <img className={styles.vectorIcon21} alt="" src="/vector30@2x.png" />
      <img className={styles.vectorIcon22} alt="" src="/vector31@2x.png" />
      <img className={styles.vectorIcon23} alt="" src="/vector32@2x.png" />
      <img className={styles.vectorIcon24} alt="" src="/vector33@2x.png" />
      <img className={styles.vectorIcon25} alt="" src="/vector34@2x.png" />
      <img className={styles.vectorIcon26} alt="" src="/vector35@2x.png" />
      <img className={styles.vectorIcon27} alt="" src="/vector36@2x.png" />
      <img className={styles.vectorIcon28} alt="" src="/vector37@2x.png" />
      <img className={styles.vectorIcon29} alt="" src="/vector38@2x.png" />
      <img className={styles.vectorIcon30} alt="" src="/vector39@2x.png" />
      <img className={styles.vectorIcon31} alt="" src="/vector40@2x.png" />
      <img className={styles.vectorIcon32} alt="" src="/vector41@2x.png" />
      <img className={styles.vectorIcon33} alt="" src="/vector42@2x.png" />
      <img className={styles.vectorIcon34} alt="" src="/vector43@2x.png" />
      <img className={styles.vectorIcon35} alt="" src="/vector44@2x.png" />
      <img className={styles.vectorIcon36} alt="" src="/vector45@2x.png" />
      <img className={styles.vectorIcon37} alt="" src="/vector46@2x.png" />
      <img className={styles.vectorIcon38} alt="" src="/vector47@2x.png" />
      <img className={styles.vectorIcon39} alt="" src="/vector48@2x.png" />
      <img className={styles.vectorIcon40} alt="" src="/vector49@2x.png" />
      <img className={styles.vectorIcon41} alt="" src="/vector50@2x.png" />
      <img className={styles.vectorIcon42} alt="" src="/vector51@2x.png" />
      <img className={styles.vectorIcon43} alt="" src="/vector52@2x.png" />
      <img className={styles.vectorIcon44} alt="" src="/vector53@2x.png" />
      <img className={styles.vectorIcon45} alt="" src="/vector54@2x.png" />
      <img className={styles.vectorIcon46} alt="" src="/vector55@2x.png" />
      <img className={styles.vectorIcon47} alt="" src="/vector56@2x.png" />
      <img className={styles.vectorIcon48} alt="" src="/vector57@2x.png" />
      <img className={styles.vectorIcon49} alt="" src="/vector58@2x.png" />
      <img className={styles.vectorIcon50} alt="" src="/vector59@2x.png" />
      <img className={styles.vectorIcon51} alt="" src="/vector60@2x.png" />
      <img className={styles.vectorIcon52} alt="" src="/vector61@2x.png" />
      <img className={styles.vectorIcon53} alt="" src="/vector62@2x.png" />
      <img className={styles.vectorIcon54} alt="" src="/vector63@2x.png" />
      <img className={styles.vectorIcon55} alt="" src="/vector64@2x.png" />
      <img className={styles.vectorIcon56} alt="" src="/vector65@2x.png" />
      <img className={styles.vectorIcon57} alt="" src="/vector66@2x.png" />
      <img className={styles.vectorIcon58} alt="" src="/vector67@2x.png" />
      <img className={styles.vectorIcon59} alt="" src="/vector68@2x.png" />
      <img className={styles.vectorIcon60} alt="" src="/vector69@2x.png" />
      <img className={styles.vectorIcon61} alt="" src="/vector70@2x.png" />
      <img className={styles.vectorIcon62} alt="" src="/vector71@2x.png" />
      <img className={styles.vectorIcon63} alt="" src="/vector72@2x.png" />
      <img className={styles.vectorIcon64} alt="" src="/vector73@2x.png" />
      <img className={styles.vectorIcon65} alt="" src="/vector74@2x.png" />
      <img className={styles.vectorIcon66} alt="" src="/vector75@2x.png" />
      <img className={styles.vectorIcon67} alt="" src="/vector76@2x.png" />
      <img className={styles.vectorIcon68} alt="" src="/vector77@2x.png" />
      <img className={styles.vectorIcon69} alt="" src="/vector78@2x.png" />
      <img className={styles.vectorIcon70} alt="" src="/vector79@2x.png" />
      <img className={styles.vectorIcon71} alt="" src="/vector80@2x.png" />
      <img className={styles.vectorIcon72} alt="" src="/vector81@2x.png" />
      <img className={styles.vectorIcon73} alt="" src="/vector82@2x.png" />
      <img className={styles.vectorIcon74} alt="" src="/vector83@2x.png" />
      <img className={styles.vectorIcon75} alt="" src="/vector84@2x.png" />
      <img className={styles.vectorIcon76} alt="" src="/vector85@2x.png" />
      <img className={styles.vectorIcon77} alt="" src="/vector86@2x.png" />
      <img className={styles.vectorIcon78} alt="" src="/vector87@2x.png" />
      <img className={styles.vectorIcon79} alt="" src="/vector88@2x.png" />
      <img className={styles.vectorIcon80} alt="" src="/vector89@2x.png" />
      <img className={styles.vectorIcon81} alt="" src="/vector90@2x.png" />
      <img className={styles.vectorIcon82} alt="" src="/vector91@2x.png" />
      <img className={styles.vectorIcon83} alt="" src="/vector92@2x.png" />
      <img className={styles.vectorIcon84} alt="" src="/vector93@2x.png" />
      <img className={styles.vectorIcon85} alt="" src="/vector94@2x.png" />
      <img className={styles.vectorIcon86} alt="" src="/vector95@2x.png" />
      <img className={styles.vectorIcon87} alt="" src="/vector96@2x.png" />
      <img className={styles.vectorIcon88} alt="" src="/vector97@2x.png" />
      <img className={styles.vectorIcon89} alt="" src="/vector98@2x.png" />
      <img className={styles.vectorIcon90} alt="" src="/vector99@2x.png" />
      <img className={styles.vectorIcon91} alt="" src="/vector100@2x.png" />
      <img className={styles.vectorIcon92} alt="" src="/vector101@2x.png" />
      <img className={styles.vectorIcon93} alt="" src="/vector102@2x.png" />
      <img className={styles.vectorIcon94} alt="" src="/vector103@2x.png" />
      <img className={styles.vectorIcon95} alt="" src="/vector104@2x.png" />
      <img className={styles.vectorIcon96} alt="" src="/vector105@2x.png" />
      <img className={styles.vectorIcon97} alt="" src="/vector106@2x.png" />
      <img className={styles.vectorIcon98} alt="" src="/vector107@2x.png" />
      <img className={styles.vectorIcon99} alt="" src="/vector108@2x.png" />
      <img className={styles.vectorIcon100} alt="" src="/vector109@2x.png" />
      <img className={styles.vectorIcon101} alt="" src="/vector110@2x.png" />
      <img className={styles.vectorIcon102} alt="" src="/vector111@2x.png" />
      <img className={styles.vectorIcon103} alt="" src="/vector112@2x.png" />
      <img className={styles.vectorIcon104} alt="" src="/vector113@2x.png" />
      <img className={styles.vectorIcon105} alt="" src="/vector114@2x.png" />
      <img className={styles.vectorIcon106} alt="" src="/vector115@2x.png" />
      <img className={styles.vectorIcon107} alt="" src="/vector116@2x.png" />
      <img className={styles.vectorIcon108} alt="" src="/vector117@2x.png" />
      <img className={styles.vectorIcon109} alt="" src="/vector118@2x.png" />
      <img className={styles.vectorIcon110} alt="" src="/vector119@2x.png" />
      <img className={styles.vectorIcon111} alt="" src="/vector120@2x.png" />
      <img className={styles.vectorIcon112} alt="" src="/vector121@2x.png" />
      <img className={styles.vectorIcon113} alt="" src="/vector122@2x.png" />
      <img className={styles.vectorIcon114} alt="" src="/vector123@2x.png" />
      <img className={styles.vectorIcon115} alt="" src="/vector124@2x.png" />
      <img className={styles.vectorIcon116} alt="" src="/vector125@2x.png" />
      <img className={styles.vectorIcon117} alt="" src="/vector126@2x.png" />
      <img className={styles.vectorIcon118} alt="" src="/vector127@2x.png" />
      <img className={styles.vectorIcon119} alt="" src="/vector128@2x.png" />
      <img className={styles.vectorIcon120} alt="" src="/vector129@2x.png" />
      <img className={styles.vectorIcon121} alt="" src="/vector130@2x.png" />
      <img className={styles.vectorIcon122} alt="" src="/vector131@2x.png" />
      <img className={styles.vectorIcon123} alt="" src="/vector132@2x.png" />
      <img className={styles.vectorIcon124} alt="" src="/vector133@2x.png" />
      <img className={styles.vectorIcon125} alt="" src="/vector134@2x.png" />
      <img className={styles.vectorIcon126} alt="" src="/vector135@2x.png" />
      <img className={styles.vectorIcon127} alt="" src="/vector136@2x.png" />
      <img className={styles.vectorIcon128} alt="" src="/vector137@2x.png" />
      <img className={styles.vectorIcon129} alt="" src="/vector138@2x.png" />
      <img className={styles.vectorIcon130} alt="" src="/vector139@2x.png" />
      <img className={styles.vectorIcon131} alt="" src="/vector140@2x.png" />
      <img className={styles.vectorIcon132} alt="" src="/vector141@2x.png" />
      <img className={styles.vectorIcon133} alt="" src="/vector142@2x.png" />
      <img className={styles.vectorIcon134} alt="" src="/vector143@2x.png" />
      <img className={styles.vectorIcon135} alt="" src="/vector144@2x.png" />
      <img className={styles.vectorIcon136} alt="" src="/vector145@2x.png" />
      <img className={styles.vectorIcon137} alt="" src="/vector146@2x.png" />
      <img className={styles.vectorIcon138} alt="" src="/vector147@2x.png" />
      <img className={styles.vectorIcon139} alt="" src="/vector148@2x.png" />
      <img className={styles.vectorIcon140} alt="" src="/vector149@2x.png" />
      <img className={styles.vectorIcon141} alt="" src="/vector150@2x.png" />
      <img className={styles.vectorIcon142} alt="" src="/vector151@2x.png" />
      <img className={styles.vectorIcon143} alt="" src="/vector152@2x.png" />
      <img className={styles.vectorIcon144} alt="" src="/vector153@2x.png" />
      <img className={styles.vectorIcon145} alt="" src="/vector154@2x.png" />
      <img className={styles.vectorIcon146} alt="" src="/vector155@2x.png" />
      <img className={styles.vectorIcon147} alt="" src="/vector156@2x.png" />
      <img className={styles.vectorIcon148} alt="" src="/vector157@2x.png" />
      <img className={styles.vectorIcon149} alt="" src="/vector158@2x.png" />
      <img className={styles.vectorIcon150} alt="" src="/vector159@2x.png" />
      <img className={styles.vectorIcon151} alt="" src="/vector160@2x.png" />
      <img className={styles.vectorIcon152} alt="" src="/vector161@2x.png" />
      <img className={styles.vectorIcon153} alt="" src="/vector162@2x.png" />
      <img className={styles.vectorIcon154} alt="" src="/vector163@2x.png" />
      <img className={styles.vectorIcon155} alt="" src="/vector164@2x.png" />
      <img className={styles.vectorIcon156} alt="" src="/vector165@2x.png" />
      <img className={styles.vectorIcon157} alt="" src="/vector166@2x.png" />
      <img className={styles.vectorIcon158} alt="" src="/vector167@2x.png" />
      <img className={styles.vectorIcon159} alt="" src="/vector168@2x.png" />
      <img className={styles.vectorIcon160} alt="" src="/vector169@2x.png" />
      <img className={styles.vectorIcon161} alt="" src="/vector170@2x.png" />
      <img className={styles.vectorIcon162} alt="" src="/vector171@2x.png" />
      <img className={styles.vectorIcon163} alt="" src="/vector172@2x.png" />
      <img className={styles.vectorIcon164} alt="" src="/vector173@2x.png" />
      <img className={styles.vectorIcon165} alt="" src="/vector174@2x.png" />
      <img className={styles.vectorIcon166} alt="" src="/vector175@2x.png" />
      <img className={styles.vectorIcon167} alt="" src="/vector176@2x.png" />
      <img className={styles.vectorIcon168} alt="" src="/vector177@2x.png" />
      <img className={styles.vectorIcon169} alt="" src="/vector178@2x.png" />
      <img className={styles.vectorIcon170} alt="" src="/vector179@2x.png" />
      <img className={styles.vectorIcon171} alt="" src="/vector180@2x.png" />
    </div>
  );
};

export default IllustrationBloggingBlogCo;
